
FROM nginx:alpine
RUN rm -rf /usr/share/nginx/html/*
COPY index.html /usr/share/nginx/html/
COPY login.html /usr/share/nginx/html/
COPY register.html /usr/share/nginx/html/
COPY welcome.html /usr/share/nginx/html/
COPY app.js /usr/share/nginx/html/
COPY login.js /usr/share/nginx/html/
COPY register.js /usr/share/nginx/html/
