version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: backend-app
    expose:
      - "5001"
    environment:
      - MONGO_URL=mongodb://mongo:27017/logindb
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: frontend-app
    ports:
      - "8080:80"  # Serve static frontend separately on port 8080

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend

volumes:
  mongo-data:
